# Generated by Django 5.0.7 on 2024-07-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('camera_type', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=50)),
                ('sensor', models.CharField(max_length=50)),
                ('uses', models.CharField(max_length=200)),
            ],
        ),
    ]
